### ISSUE TITLE
age categories

### ISSUE THREAD

**Issue by PaulC91** [epicentre-msf/simulated-data#1]
Not sure if this was on purpose to create the "0 - 11 months" group but `between()` is inclusive so the first line would include 1 year olds and the second only 2-4 year olds.

https://github.com/epicentre-msf/fake-data/blob/78179866dae368660e92ba09d13ebf86e6c63660/R/gen_linelist.R#L61-L62

**Comment by hugzsoubrier** [comment]
yeah it's made on purpose, there are no 1 year old in the dataset - it's linked to the age generation by `{simulist}` that can only take whole integers.
